/* Every word of the shell, in the four languages the app has today.
   The templates inside the frames carry their own copy — that lives in the generated
   language packs under src/gvpro/lang/ and never here. */

export const UI = {
  en: {
    dir: 'ltr',
    slogan: 'your idea, your app',
    ph: "e.g. Moshe's Barbershop",
    hintName: 'Your business name',
    barber: 'Barber', clinic: 'Clinic', bakery: 'Bakery', yoga: 'Yoga', garage: 'Garage',
    swipe: 'swipe to see all 12 styles', prev: 'Previous styles', next: 'More styles',
    lang: 'Language', share: 'Share', close: 'Close', back: 'Back',
    copied: 'Link copied', copyFail: 'Could not copy the link',
    wantSite: 'I want this site',
    wantApp: 'I want an app',
    formSiteTitle: 'Your new site',
    formAppTitle: 'Your app with booking and orders',
    formNote: 'Leave your details and we answer on WhatsApp.',
    fName: 'Your name', fBiz: 'Business name', fWa: 'WhatsApp number', fMsg: 'Anything to add? (optional)',
    fWaPh: '+972 50 123 4567',
    send: 'Send', sending: 'Sending…',
    errName: 'Please write your name.',
    errBiz: 'Please write the name of the business.',
    errWa: 'That does not look like a phone number.',
    errSave: 'It did not go through. Try again.',
    thanks: 'Got it.',
    thanksNote: 'We have your details. Open WhatsApp and we carry on there — it is the fastest way.',
    openWa: 'Continue on WhatsApp',
    seePackages: 'See the app packages',
    packages: 'Start ₪2,900 · Business ₪5,900 · Pro from ₪9,900',
    waSite: 'Hi! I want this site',
    waApp: 'Hi! I want an app with booking and orders',
    builtOn: 'Built on Base44',
    admin: 'Leads', adminOnly: 'This page is for the studio.',
    thName: 'Name', thBiz: 'Business', thWa: 'WhatsApp', thWant: 'Wants', thNiche: 'Niche',
    thStyle: 'Style', thLang: 'Lang', thStatus: 'Status', thWhen: 'When', thNote: 'Note', thPkg: 'Package',
    stNew: 'new', stContacted: 'contacted', stWon: 'won', stLost: 'lost',
    empty: 'No leads yet.',
    /* --- Site / App, the toggle over the carousel */
    modeSite: 'Site', modeApp: 'App', modeHint: 'See it as an app',
    /* --- the app demo running inside the phone */
    tabHome: 'Home', tabMine: 'Bookings', tabMineOrders: 'Orders', tabContact: 'Contact',
    installChip: 'Install on your phone',
    demoNote: 'A demo. Nothing here is really booked.',
    demoPick: 'Pick what you need', demoWhen: 'Pick a time',
    demoToday: 'Today', demoTomorrow: 'Tomorrow',
    demoConfirm: 'Confirm', demoOrderBtn: 'Place the order',
    demoBooked: 'Booked', demoOrdered: 'Ordered', demoEmpty: 'Nothing here yet.',
    demoTotal: 'Total', demoAdd: 'Add', demoBack: 'Back',
    demoCall: 'Call', demoWa: 'WhatsApp', demoHours: 'Hours', demoWhere: 'Where',
    /* --- the screen that opens before the app form */
    pitchTitle: 'Your own app', pitchFor: 'for a {trade}',
    pitchBook: 'Bookings your customers make themselves, day and night.',
    pitchOrder: 'Orders your customers place themselves, day and night.',
    pitchDash: 'An owner screen: who booked, what was ordered, what is left today.',
    pitchWa: 'Every new one reaches you on WhatsApp the moment it happens.',
    pitchInstall: 'It installs on a phone from a link. No store, no waiting for approval.',
    pitchLangs: 'Hebrew and English, and it reads right to left properly.',
    pitchOwn: 'Built on Base44 — the app account belongs to you.',
    pkgTitle: 'Three ways in',
    pkgStart: 'Start', pkgStartLine: 'One trade, booking or orders, installs on the phone.',
    pkgBusiness: 'Business', pkgBusinessLine: 'Plus the owner screen, WhatsApp notices and your own look.',
    pkgPro: 'Pro', pkgProLine: 'Payments, more than one branch, and whatever else the business really needs.',
    pkgFrom: 'from', pkgPicked: 'Chosen',
    pitchGo: 'Leave my details',
    names: {},
  },
  he: {
    dir: 'rtl',
    slogan: 'הרעיון שלך, האפליקציה שלך',
    ph: 'למשל: המספרה של משה',
    hintName: 'איך קוראים לעסק?',
    barber: 'מספרה', clinic: 'מרפאה', bakery: 'מאפייה', yoga: 'יוגה', garage: 'מוסך',
    swipe: 'החליקו כדי לראות את כל 12 הסגנונות', prev: 'הסגנונות הקודמים', next: 'עוד סגנונות',
    lang: 'שפה', share: 'שיתוף', close: 'סגירה', back: 'חזרה',
    copied: 'הקישור הועתק', copyFail: 'לא הצלחנו להעתיק את הקישור',
    wantSite: 'זה האתר שלי',
    wantApp: 'אני רוצה אפליקציה',
    formSiteTitle: 'האתר החדש שלכם',
    formAppTitle: 'האפליקציה שלכם עם תורים והזמנות',
    formNote: 'השאירו פרטים ונחזור אליכם בוואטסאפ.',
    fName: 'השם שלכם', fBiz: 'שם העסק', fWa: 'מספר וואטסאפ', fMsg: 'משהו להוסיף? (לא חובה)',
    fWaPh: '050-123-4567',
    send: 'שליחה', sending: 'שולח…',
    errName: 'כתבו את השם שלכם.',
    errBiz: 'כתבו את שם העסק.',
    errWa: 'זה לא נראה כמו מספר טלפון.',
    errSave: 'זה לא נשלח. נסו שוב.',
    thanks: 'קיבלנו.',
    thanksNote: 'הפרטים אצלנו. פתחו וואטסאפ ונמשיך שם — זו הדרך הכי מהירה.',
    openWa: 'ממשיכים בוואטסאפ',
    seePackages: 'לחבילות האפליקציה',
    packages: 'סטארט ₪2,900 · ביזנס ₪5,900 · פרו מ־₪9,900',
    waSite: 'היי! אני רוצה את האתר הזה',
    waApp: 'היי! אני רוצה אפליקציה עם תורים והזמנות',
    builtOn: 'נבנה על Base44',
    admin: 'לידים', adminOnly: 'הדף הזה לסטודיו.',
    thName: 'שם', thBiz: 'עסק', thWa: 'וואטסאפ', thWant: 'רוצה', thNiche: 'תחום',
    thStyle: 'סגנון', thLang: 'שפה', thStatus: 'סטטוס', thWhen: 'מתי', thNote: 'הערה', thPkg: 'חבילה',
    stNew: 'חדש', stContacted: 'יצרנו קשר', stWon: 'נסגר', stLost: 'לא יצא',
    empty: 'אין לידים עדיין.',
    modeSite: 'אתר', modeApp: 'אפליקציה', modeHint: 'ראו את זה כאפליקציה',
    tabHome: 'בית', tabMine: 'תורים', tabMineOrders: 'הזמנות', tabContact: 'קשר',
    installChip: 'התקינו בטלפון',
    demoNote: 'הדגמה. שום דבר כאן לא נקבע באמת.',
    demoPick: 'בחרו מה שצריך', demoWhen: 'בחרו שעה',
    demoToday: 'היום', demoTomorrow: 'מחר',
    demoConfirm: 'אישור', demoOrderBtn: 'שליחת ההזמנה',
    demoBooked: 'נקבע', demoOrdered: 'הוזמן', demoEmpty: 'עדיין אין כאן כלום.',
    demoTotal: 'סה״כ', demoAdd: 'הוספה', demoBack: 'חזרה',
    demoCall: 'חיוג', demoWa: 'וואטסאפ', demoHours: 'שעות', demoWhere: 'איפה',
    pitchTitle: 'אפליקציה משלכם', pitchFor: 'ל{trade}',
    pitchBook: 'הלקוחות קובעים תור בעצמם, ביום ובלילה.',
    pitchOrder: 'הלקוחות מזמינים בעצמם, ביום ובלילה.',
    pitchDash: 'מסך לבעלים: מי קבע, מה הוזמן, מה נשאר להיום.',
    pitchWa: 'כל חדש מגיע אליכם לוואטסאפ ברגע שהוא קורה.',
    pitchInstall: 'מתקינה בטלפון מקישור. בלי חנות ובלי להמתין לאישור.',
    pitchLangs: 'עברית ואנגלית, וימין לשמאל כמו שצריך.',
    pitchOwn: 'בנוי על Base44 — חשבון האפליקציה שייך לכם.',
    pkgTitle: 'שלוש דרכים להתחיל',
    pkgStart: 'סטארט', pkgStartLine: 'תחום אחד, תורים או הזמנות, מתקינה בטלפון.',
    pkgBusiness: 'ביזנס', pkgBusinessLine: 'בנוסף מסך לבעלים, התראות בוואטסאפ ועיצוב משלכם.',
    pkgPro: 'פרו', pkgProLine: 'תשלומים, יותר מסניף אחד, וכל מה שהעסק באמת צריך.',
    pkgFrom: 'מ־', pkgPicked: 'נבחר',
    pitchGo: 'להשאיר פרטים',
    names: { barber: 'המספרה של משה', clinic: 'מרפאת השיניים של גל', bakery: 'מאפיית שרה', yoga: 'יוגה על הים', garage: 'מוסך אבי' },
  },
  ru: {
    dir: 'ltr',
    slogan: 'ваша идея — ваше приложение',
    ph: 'Например: Барбершоп Моше',
    hintName: 'Как называется ваш бизнес?',
    barber: 'Барбер', clinic: 'Клиника', bakery: 'Пекарня', yoga: 'Йога', garage: 'Автосервис',
    swipe: 'листайте, чтобы увидеть все 12 стилей', prev: 'Предыдущие стили', next: 'Ещё стили',
    lang: 'Язык', share: 'Поделиться', close: 'Закрыть', back: 'Назад',
    copied: 'Ссылка скопирована', copyFail: 'Не удалось скопировать ссылку',
    wantSite: 'Хочу этот сайт',
    wantApp: 'Хочу приложение',
    formSiteTitle: 'Ваш новый сайт',
    formAppTitle: 'Ваше приложение с записью и заказами',
    formNote: 'Оставьте контакты — ответим в WhatsApp.',
    fName: 'Ваше имя', fBiz: 'Название бизнеса', fWa: 'Номер WhatsApp', fMsg: 'Что-то добавить? (необязательно)',
    fWaPh: '+972 50 123 4567',
    send: 'Отправить', sending: 'Отправляем…',
    errName: 'Напишите ваше имя.',
    errBiz: 'Напишите название бизнеса.',
    errWa: 'Это не похоже на номер телефона.',
    errSave: 'Не отправилось. Попробуйте ещё раз.',
    thanks: 'Получили.',
    thanksNote: 'Контакты у нас. Откройте WhatsApp — там продолжим, так быстрее всего.',
    openWa: 'Продолжить в WhatsApp',
    seePackages: 'Пакеты приложений',
    packages: 'Start ₪2 900 · Business ₪5 900 · Pro от ₪9 900',
    waSite: 'Здравствуйте! Хочу этот сайт',
    waApp: 'Здравствуйте! Хочу приложение с записью и заказами',
    builtOn: 'Сделано на Base44',
    admin: 'Лиды', adminOnly: 'Эта страница — для студии.',
    thName: 'Имя', thBiz: 'Бизнес', thWa: 'WhatsApp', thWant: 'Хочет', thNiche: 'Ниша',
    thStyle: 'Стиль', thLang: 'Язык', thStatus: 'Статус', thWhen: 'Когда', thNote: 'Заметка', thPkg: 'Пакет',
    stNew: 'новый', stContacted: 'связались', stWon: 'выиграли', stLost: 'не вышло',
    empty: 'Лидов пока нет.',
    modeSite: 'Сайт', modeApp: 'Приложение', modeHint: 'Посмотреть как приложение',
    tabHome: 'Главная', tabMine: 'Записи', tabMineOrders: 'Заказы', tabContact: 'Контакты',
    installChip: 'Установить на телефон',
    demoNote: 'Это демо. Ничего на самом деле не записано.',
    demoPick: 'Выберите, что нужно', demoWhen: 'Выберите время',
    demoToday: 'Сегодня', demoTomorrow: 'Завтра',
    demoConfirm: 'Подтвердить', demoOrderBtn: 'Оформить заказ',
    demoBooked: 'Записано', demoOrdered: 'Заказано', demoEmpty: 'Здесь пока пусто.',
    demoTotal: 'Итого', demoAdd: 'Добавить', demoBack: 'Назад',
    demoCall: 'Позвонить', demoWa: 'WhatsApp', demoHours: 'Часы', demoWhere: 'Адрес',
    pitchTitle: 'Своё приложение', pitchFor: 'для {trade}',
    pitchBook: 'Клиенты записываются сами, днём и ночью.',
    pitchOrder: 'Клиенты заказывают сами, днём и ночью.',
    pitchDash: 'Экран владельца: кто записался, что заказали, что осталось на сегодня.',
    pitchWa: 'Каждая новая запись приходит вам в WhatsApp сразу.',
    pitchInstall: 'Ставится на телефон по ссылке. Без магазина и без ожидания одобрения.',
    pitchLangs: 'Иврит и английский, и справа налево — как надо.',
    pitchOwn: 'Сделано на Base44 — аккаунт приложения принадлежит вам.',
    pkgTitle: 'Три способа начать',
    pkgStart: 'Start', pkgStartLine: 'Одно направление, запись или заказы, ставится на телефон.',
    pkgBusiness: 'Business', pkgBusinessLine: 'Плюс экран владельца, уведомления в WhatsApp и свой дизайн.',
    pkgPro: 'Pro', pkgProLine: 'Оплаты, несколько точек и всё остальное, что бизнесу правда нужно.',
    pkgFrom: 'от', pkgPicked: 'Выбрано',
    pitchGo: 'Оставить контакты',
    names: { barber: 'Барбершоп Моше', clinic: 'Стоматология Гал', bakery: 'Пекарня Сары', yoga: 'Йога у моря', garage: 'Автосервис Ави' },
  },
  ar: {
    dir: 'rtl',
    slogan: 'فكرتك، تطبيقك',
    ph: 'مثلاً: صالون موسى',
    hintName: 'ما اسم نشاطك التجاري؟',
    barber: 'حلاقة', clinic: 'عيادة', bakery: 'مخبز', yoga: 'يوغا', garage: 'كراج',
    swipe: 'اسحب لترى الأنماط الـ12 كلها', prev: 'الأنماط السابقة', next: 'أنماط أخرى',
    lang: 'اللغة', share: 'مشاركة', close: 'إغلاق', back: 'رجوع',
    copied: 'تم نسخ الرابط', copyFail: 'تعذّر نسخ الرابط',
    wantSite: 'هذا موقعي',
    wantApp: 'أريد تطبيقاً',
    formSiteTitle: 'موقعك الجديد',
    formAppTitle: 'تطبيقك للحجوزات والطلبات',
    formNote: 'اترك بياناتك ونرد عليك في واتساب.',
    fName: 'اسمك', fBiz: 'اسم النشاط', fWa: 'رقم واتساب', fMsg: 'شيء تضيفه؟ (اختياري)',
    fWaPh: '050-123-4567',
    send: 'إرسال', sending: 'جارٍ الإرسال…',
    errName: 'اكتب اسمك من فضلك.',
    errBiz: 'اكتب اسم النشاط من فضلك.',
    errWa: 'هذا لا يبدو رقم هاتف.',
    errSave: 'لم يُرسل. حاول مرة أخرى.',
    thanks: 'وصلنا.',
    thanksNote: 'بياناتك عندنا. افتح واتساب ونكمل هناك — إنها أسرع طريقة.',
    openWa: 'نكمل في واتساب',
    seePackages: 'باقات التطبيق',
    packages: 'Start ₪2,900 · Business ₪5,900 · Pro من ₪9,900',
    waSite: 'مرحباً! أريد هذا الموقع',
    waApp: 'مرحباً! أريد تطبيقاً للحجوزات والطلبات',
    builtOn: 'مبني على Base44',
    admin: 'العملاء', adminOnly: 'هذه الصفحة للاستوديو.',
    thName: 'الاسم', thBiz: 'النشاط', thWa: 'واتساب', thWant: 'يريد', thNiche: 'المجال',
    thStyle: 'النمط', thLang: 'اللغة', thStatus: 'الحالة', thWhen: 'متى', thNote: 'ملاحظة', thPkg: 'الباقة',
    stNew: 'جديد', stContacted: 'تواصلنا', stWon: 'تم', stLost: 'لم ينجح',
    empty: 'لا يوجد عملاء بعد.',
    modeSite: 'موقع', modeApp: 'تطبيق', modeHint: 'شاهده كتطبيق',
    tabHome: 'الرئيسية', tabMine: 'حجوزاتي', tabMineOrders: 'طلباتي', tabContact: 'اتصال',
    installChip: 'ثبّته على هاتفك',
    demoNote: 'عرض تجريبي. لا شيء هنا محجوز فعلاً.',
    demoPick: 'اختر ما تحتاجه', demoWhen: 'اختر وقتاً',
    demoToday: 'اليوم', demoTomorrow: 'غداً',
    demoConfirm: 'تأكيد', demoOrderBtn: 'إرسال الطلب',
    demoBooked: 'تم الحجز', demoOrdered: 'تم الطلب', demoEmpty: 'لا شيء هنا بعد.',
    demoTotal: 'المجموع', demoAdd: 'إضافة', demoBack: 'رجوع',
    demoCall: 'اتصال', demoWa: 'واتساب', demoHours: 'الساعات', demoWhere: 'العنوان',
    pitchTitle: 'تطبيق خاص بك', pitchFor: 'لـ{trade}',
    pitchBook: 'الزبائن يحجزون بأنفسهم، ليلاً ونهاراً.',
    pitchOrder: 'الزبائن يطلبون بأنفسهم، ليلاً ونهاراً.',
    pitchDash: 'شاشة لصاحب العمل: من حجز، ماذا طُلب، وماذا بقي اليوم.',
    pitchWa: 'كل جديد يصلك على واتساب فور حدوثه.',
    pitchInstall: 'يُثبّت على الهاتف من رابط. بلا متجر وبلا انتظار موافقة.',
    pitchLangs: 'عبرية وإنجليزية، ومن اليمين إلى اليسار كما يجب.',
    pitchOwn: 'مبني على Base44 — حساب التطبيق ملكك.',
    pkgTitle: 'ثلاث طرق للبدء',
    pkgStart: 'Start', pkgStartLine: 'مجال واحد، حجوزات أو طلبات، يُثبّت على الهاتف.',
    pkgBusiness: 'Business', pkgBusinessLine: 'إضافةً إلى شاشة المالك وإشعارات واتساب وتصميم خاص بك.',
    pkgPro: 'Pro', pkgProLine: 'مدفوعات، أكثر من فرع، وكل ما يحتاجه العمل فعلاً.',
    pkgFrom: 'من', pkgPicked: 'مختار',
    pitchGo: 'أترك بياناتي',
    names: { barber: 'صالون موسى', clinic: 'عيادة غال للأسنان', bakery: 'مخبز سارة', yoga: 'يوغا البحر', garage: 'كراج أبي' },
  },
};

export function tr(lang, key) {
  const pack = UI[lang] || UI.en;
  return pack[key] != null ? pack[key] : UI.en[key];
}

/* The example name in the field's own language, so an empty field still shows a real site. */
export function sampleName(lang, niche) {
  const pack = UI[lang] || UI.en;
  return (pack.names && pack.names[niche]) || '';
}
